spring.application.name=backend

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/EmergenSyncDB?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=mysql123

spring.jpa.hibernate.ddl-auto=update

# JWT settings for authentication
jwt.auth.secret=MySecureAuthenticationSecretKeyForJWT2025@&91234568##88`~8800&**EmergenSync**$$$JWT2025#